id: A8603690B
title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary of the
  Chronicles of Padma, The Life and Liberation of the Precious Guru of Uḍḍiyāna'
type: translation
pechas:
- IED54B8B6
- I88E3ECC3
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:36:23.020048
  last_modified_at: 2023-01-04 12:36:23.020055
  collections:
  - Jamyang Khyentse Wangpo Series
  - Works of Tibetan Masters
alignment_to_base:
  IED54B8B6/C54F: E34E
  I88E3ECC3/C81B: E34E
